### ISSUE TITLE
Hello, can you provide the version of keras and other tool libraries you use?

### ISSUE THREAD

**Issue by weihaoning** [monologg/DDI-project#1]
First problem is，can you provide the version of keras and other tool libraries you use？
Another problem is ，when i train the cnn,mccnn and rnn, the spyder report an error “AttributeError: 'list' object has no attribute 'shape'”，I think it should be a problem when entering data. Have you encountered this problem? And i cannot solve it, please help me ,thank you

**Comment by monologg** [comment]
I use the keras==2.2.4 and tensorflow-gpu==1.11.0. It works well on this version, but if the version of the keras is lower than this, some error has happened. I think keras ver 2.2.4 automatically change list to numpy type, but the lower version doesn't. I'l update  the requirements.txt file and fix this problem as soon as possible:) (Actually this code is still on testing.)

**Comment by monologg** [comment]
I use the keras==2.2.4 and tensorflow-gpu==1.11.0. It works well on this version, but if the version of the keras is lower than this, some error has happened. I think keras ver 2.2.4 automatically change list to numpy type, but the lower version doesn't. I'l update the requirements.txt file and fix this problem as soon as possible:) (Actually this code is still on testing.)

**Comment by monologg** [comment]
Can you tell me keras version and tensorflow version that you are using?

**Comment by weihaoning** [comment]
Thank you for your updated code later. it do not report some error during training. I used keras2.1 and tensorflow-cpu1.2.1. When I training with the gpu version of tensorflow1.2.0. it has an error:"An error occurred while starting the kernel. ", but I guess this should be a problem with Spyder, it doesn't matter to the code.

**Comment by monologg** [comment]
Ok then i'll close the issue:) Thanks
