### ISSUE TITLE
create TSV

### ISSUE THREAD

**Issue by niloofar-kh** [monologg/DDI-project#2]
Hi
can I have your tsv file creation and preprocessing code?
I want to re_run your code with another dataset (same data) but it is impossible because of our tsv headers not the same with your file.

**Comment by monologg** [comment]
Sorry for the late reply. I have no preprocessing code, bring the data from [this link](https://github.com/arwhirang/DDI-recursive-NN/tree/master/Demo/data). 
If you want to change the data loading, I recommend you to change load_sentence() in load_data_ddi.py slightly. [code link](https://github.com/monologg/DDI-project/blob/master/load_data_ddi.py#L37)
